networks:
  rspec:
  web:


services:
  web: 
    build: .
    command: hanami server --host=0.0.0.0
    ports:
      - 2300:2300
    volumes:
      - ./:/usr/local/app
    depends_on:
      - db
    networks:
      - web


  rspec:
    build: .
    command: hanami server --host=0.0.0.2
    ports:
      - 2300:2300
    volumes:
      - ./:/usr/local/app
    depends_on:
      - db_rspec
    networks:
      - rspec


  new: 
    build: .
    command: hanami new Bookshelf
    ports:
      - 2300:2300
    volumes:
      - ./:/usr/local/app
    depends_on:
      - db


  db_rspec:
    image: postgres:10.4-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - rspec

      
  db:
    image: postgres:10.4-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - web

