#https://www.useo.pl/blog/2023/03/setting-up-hanami-and-postgres-with-docker-compose

volumes:
  postgres-data-db:
  postgres-data-test:

networks:
  web:
  test:

services:
  web: &web
    image: simple-api
    command: hanami server
    env_file: .env.development
    volumes:
      - ./:/usr/local/app
    depends_on:
      - db
    networks:
      - web

  rspec: 
    <<: *web
    env_file: .env.test
    volumes:
      - ./:/usr/local/app
    depends_on:
      - db_test
    networks:
      - test

  db:
    image: postgres:10.4-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - postgres-data-db:/var/lib/postgresql/data
    networks:
      - web

  db_test:
    image: postgres:10.4-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - postgres-data-test:/var/lib/postgresql/data
    networks:
      - test

      

        
